# apiVersion: v1
# kind: Service
# metadata:
#   name: elasticsearch
#   namespace: monitoring
#   labels:
#     app: elasticsearch
# spec:
#   ports:
#     - port: 9200
#       name: http
#     - port: 9300
#       name: transport
#   selector:
#     app: elasticsearch  
#   type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: elasticsearch-sa
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 2
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              value: infy@123
          ports:
            - containerPort: 9200  # HTTP port
              name: http
              # name: https
            - containerPort: 9300  # Transport port
              name: transport
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            # - name: server-crt
            #   mountPath: /usr/share/elasticsearch/config/server.crt
            #   subPath: server.crt 
            # - name: server-key
            #   mountPath: /usr/share/elasticsearch/config/server.key
            #   subPath: server.key 
            # - name: ca-crt   
            #   mountPath: /usr/share/elasticsearch/config/ca.crt
            #   subPath: ca.crt         
      volumes:
        - name: config-volume
          configMap:
            name: elasticsearch-config
        # - name: server-crt
        #   secret:
        #     secretName: server-crt
        # - name: server-key
        #   secret:
        #     secretName: server-key
        # - name: ca-crt
        #   secret:
        #     secretName: ca-crt       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: monitoring
data:
  elasticsearch.yml: |
    cluster.name: dev-qa-cluster
    node.name: elasticsearch-0
    network.host: 0.0.0.0
    http.port: 9200  # Specify the HTTP port (default is 9200)
    transport.port: 9300  # Specify the transport port (default is 9300)
    # Disable SSL/TLS settings if not needed
    xpack.security.enabled: false
    # xpack.security.enrollment.enabled: true
    # xpack.security.authc.api_key.enabled: true
    # xpack.security.http.ssl.enabled: true
    # xpack.security.http.ssl.verification_mode: "certificate"
    # xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/server.crt
    # xpack.security.http.ssl.key: /usr/share/elasticsearch/config/server.key
    # xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt

    # xpack.security.transport.ssl.enabled: true
    # xpack.security.transport.ssl.verification_mode: "certificate"
    # xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/server.key
    # xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/server.crt
    # xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt

