apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring
  name: elasticsearch-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-rolebinding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: elasticsearch-sa
  namespace: monitoring
roleRef:
  kind: Role
  name: elasticsearch-role
  apiGroup: rbac.authorization.k8s.io
